begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select is((select sum(jsonb_array_length(payload->'programs')) from public.programplan_catalogs),29::bigint,'pinned catalog contains exactly 29 programs');
select has_function('public','phase5_programplan_choice_blocks',array['jsonb'],'internal block resolver exists');
create function pg_temp.choice_reference(p jsonb,o jsonb) returns jsonb language sql as $$
select jsonb_build_object('catalogId',(select catalog_id from public.programplan_catalogs limit 1),'programRef',jsonb_build_object('code',p->'code','version',p->'version'),'orientationCode',o->'code','startedOn','2027-08-17','specializationRefs','[]'::jsonb,'choiceBlocks',
case p->>'code' when 'EK25' then '[{"id":"mosp","kind":"modernLanguage","points":100,"name":"Moderna språk"}]'::jsonb
 when 'HU25' then '[{"id":"mosp","kind":"modernLanguage","points":200,"name":"Moderna språk"}]'::jsonb
 when 'NA25' then '[{"id":"mosp","kind":"modernLanguage","points":100,"name":"Moderna språk"}]'::jsonb
 when 'SA25' then '[{"id":"mosp","kind":"modernLanguage","points":200,"name":"Moderna språk"}]'::jsonb
 when 'SM25' then '[{"id":"mosp","kind":"modernLanguage","points":300,"name":"Moderna språk"}]'::jsonb else '[]'::jsonb end
 ||case o->>'code' when 'HUSPK' then '[{"id":"sprk","kind":"languageSubject","points":300,"name":"Språkämne"}]'::jsonb when 'NANAA' then '[{"id":"nave","kind":"naturalScience","points":100,"name":"Ett naturvetenskapligt ämne"}]'::jsonb else '[]'::jsonb end
 ||'[{"id":"iv1","kind":"individualChoice","points":200,"name":"Individuellt val"}]'::jsonb)
$$;
create temporary table choice_results(test_result text);
do $$declare p jsonb;o jsonb;r jsonb;rows jsonb;n integer:=0;
begin
for p in select value from public.programplan_catalogs c,lateral jsonb_array_elements(c.payload->'programs') loop
 for o in select value from jsonb_array_elements(case when jsonb_array_length(p->'orientations')=0 then '[null]'::jsonb else p->'orientations' end) loop
 n:=n+1;r:=pg_temp.choice_reference(p,o);
 insert into choice_results values(is(public.phase5_resolve_programplan_basis(r)->>'status','resolved',(p->>'code')||'/'||coalesce(o->>'code','-')||' v2 resolves'));
 if public.phase5_resolve_programplan_basis(r)->>'status'='resolved' then
 rows:=public.phase5_programplan_term_rows(r);
 insert into choice_results values(is((select count(*) from jsonb_array_elements(rows) x where x->>'key' like 'alternative:foundation:%' and x->'points'='100'::jsonb),3::bigint,'three Swedish alternatives '||(p->>'code')||'/'||coalesce(o->>'code','-')));
 insert into choice_results values(ok(not rows @> '[{"key":"meta:individualChoice"}]'::jsonb,'no legacy IV row '||(p->>'code')));
 insert into choice_results values(is((select count(*) from jsonb_array_elements(rows) x where x->>'key' like 'block:%'),jsonb_array_length(r->'choiceBlocks')::bigint,'exact block row count '||(p->>'code')));
 end if;
 end loop;
end loop;
insert into choice_results values(ok(n>29,'every orientation and orientation-free program visited'));
end$$;
select test_result from choice_results;
-- Exact legacy snapshots were captured with pg_get_functiondef inventory, before migration.
select is(public.phase5_programplan_term_rows('{"catalogId":"sha256:fa42ec44e663703bbf69ccd7b78c28d28ad275b144c57241f9f450a7a7252ace","programRef":{"code":"SA25","version":4},"orientationCode":"SABEP","startedOn":"2027-08-17","specializationRefs":[{"subjectCode":"ENGE","subjectVersion":1,"itemCode":"ENGE3000X","points":100}]}'::jsonb),'[{"key":"foundation:ENGE:1:ENGE1000X","points":100},{"key":"foundation:ENGE:1:ENGE2000X","points":100},{"key":"foundation:HIST:1:HIST1B00X","points":100},{"key":"foundation:IDRO:1:IDRO1000X","points":100},{"key":"foundation:MATE:1:MATE1B00X","points":100},{"key":"foundation:MATE:1:MATE2B00X","points":100},{"key":"foundation:NATU:1:NATU1B00X","points":100},{"key":"foundation:RELI:1:RELI1000X","points":50},{"key":"foundation:SAMH:1:SAMH1B00X","points":100},{"key":"programmeSpecific:FILS:1:FILS1000X","points":50},{"key":"programmeSpecific:PSYL:3:PSYL1000X","points":50},{"key":"orientation:LEDA:1:LEDA1000X","points":100},{"key":"orientation:PSYL:3:PSYL2000X","points":50},{"key":"orientation:SAMH:1:SAMH2000X","points":100},{"key":"orientation:SOCI:1:SOCI1000X","points":100},{"key":"orientation:SOCI:1:SOCI2000X","points":100},{"key":"specialization:ENGE:1:ENGE3000X","points":100},{"key":"meta:individualChoice","points":200},{"key":"meta:diplomaWork","points":100}]'::jsonb,'legacy SABEP exact keys points and order');
select is(public.phase5_programplan_term_rows('{"catalogId":"sha256:fa42ec44e663703bbf69ccd7b78c28d28ad275b144c57241f9f450a7a7252ace","programRef":{"code":"SA25","version":4},"orientationCode":"SAMJK","startedOn":"2027-08-17","specializationRefs":[{"subjectCode":"ENGE","subjectVersion":1,"itemCode":"ENGE3000X","points":100}]}'::jsonb),'[{"key":"foundation:ENGE:1:ENGE1000X","points":100},{"key":"foundation:ENGE:1:ENGE2000X","points":100},{"key":"foundation:HIST:1:HIST1B00X","points":100},{"key":"foundation:IDRO:1:IDRO1000X","points":100},{"key":"foundation:MATE:1:MATE1B00X","points":100},{"key":"foundation:MATE:1:MATE2B00X","points":100},{"key":"foundation:NATU:1:NATU1B00X","points":100},{"key":"foundation:RELI:1:RELI1000X","points":50},{"key":"foundation:SAMH:1:SAMH1B00X","points":100},{"key":"programmeSpecific:FILS:1:FILS1000X","points":50},{"key":"programmeSpecific:PSYL:3:PSYL1000X","points":50},{"key":"orientation:MEDP:1:MEDP1000X","points":100},{"key":"orientation:MEDP:1:MEDP2000X","points":100},{"key":"orientation:MEDI:1:MEDI1000X","points":100},{"key":"orientation:MEDI:1:MEDI2000X","points":100},{"key":"orientation:PSYL:3:PSYL2000X","points":50},{"key":"specialization:ENGE:1:ENGE3000X","points":100},{"key":"meta:individualChoice","points":200},{"key":"meta:diplomaWork","points":100}]'::jsonb,'legacy SAMJK exact keys points and order');
select is(public.phase5_programplan_term_rows('{"catalogId":"sha256:fa42ec44e663703bbf69ccd7b78c28d28ad275b144c57241f9f450a7a7252ace","programRef":{"code":"SA25","version":4},"orientationCode":"SASAP","startedOn":"2027-08-17","specializationRefs":[{"subjectCode":"ENGE","subjectVersion":1,"itemCode":"ENGE3000X","points":100}]}'::jsonb),'[{"key":"foundation:ENGE:1:ENGE1000X","points":100},{"key":"foundation:ENGE:1:ENGE2000X","points":100},{"key":"foundation:HIST:1:HIST1B00X","points":100},{"key":"foundation:IDRO:1:IDRO1000X","points":100},{"key":"foundation:MATE:1:MATE1B00X","points":100},{"key":"foundation:MATE:1:MATE2B00X","points":100},{"key":"foundation:NATU:1:NATU1B00X","points":100},{"key":"foundation:RELI:1:RELI1000X","points":50},{"key":"foundation:SAMH:1:SAMH1B00X","points":100},{"key":"programmeSpecific:FILS:1:FILS1000X","points":50},{"key":"programmeSpecific:PSYL:3:PSYL1000X","points":50},{"key":"orientation:GEOG:1:GEOG1000X","points":100},{"key":"orientation:HIST:1:HIST2A00X","points":100},{"key":"orientation:RELI:1:RELI2000X","points":50},{"key":"orientation:SAMH:1:SAMH2000X","points":100},{"key":"orientation:SAMH:1:SAMH3000X","points":100},{"key":"specialization:ENGE:1:ENGE3000X","points":100},{"key":"meta:individualChoice","points":200},{"key":"meta:diplomaWork","points":100}]'::jsonb,'legacy SASAP exact keys points and order');
create temporary table sa_choice_basis as
 select pg_temp.choice_reference(p,o)||jsonb_build_object('specializationRefs','[{"subjectCode":"ENGE","subjectVersion":1,"itemCode":"ENGE3000X","points":100},{"subjectCode":"ANIM","subjectVersion":1,"itemCode":"ANIM1000X","points":100},{"subjectCode":"ANIM","subjectVersion":1,"itemCode":"ANIM2000X","points":100}]'::jsonb) reference
 from public.programplan_catalogs c,lateral jsonb_array_elements(c.payload->'programs') p,lateral jsonb_array_elements(p->'orientations') o where p->>'code'='SA25';
select is((select sum((x->>'points')::integer) from jsonb_array_elements(public.phase5_programplan_term_rows(reference)) x),2500::bigint,'SA25 '||(reference->>'orientationCode')||' exactly 2500 points') from sa_choice_basis;
select is(public.phase5_programplan_choice_blocks(reference),
 '[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200,"part":"programmeSpecific","rowKey":"block:mosp"},{"id":"iv1","kind":"individualChoice","name":"Individuellt val","points":200,"part":"individualChoice","rowKey":"block:iv1"}]'::jsonb,'blocks expose stable keys and correct parts') from sa_choice_basis;
create function pg_temp.choice_diagnostics(blocks jsonb) returns jsonb language sql as $$
select public.phase5_resolve_programplan_basis(jsonb_set((select reference from sa_choice_basis limit 1),'{choiceBlocks}',blocks))->'diagnostics'
$$;
select is(pg_temp.choice_diagnostics('[{"id":"iv1","kind":"individualChoice","name":"IV","points":200}]'), '[{"code":"missing_slot_block"}]'::jsonb,'missing slot rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":100},{"id":"iv1","kind":"individualChoice","name":"IV","points":200}]'),'[{"code":"slot_block_mismatch"}]'::jsonb,'incorrect slot points rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":200}]'),'[{"code":"duplicate_choice_block"}]'::jsonb,'duplicate slot rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":300}]'),'[{"code":"individual_choice_points_mismatch"}]'::jsonb,'IV over 200 rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"unknown","name":"IV","points":200}]'),'[{"code":"invalid_choice_blocks"}]'::jsonb,'unknown block kind rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"specialization","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":200}]'),'[{"code":"slot_block_mismatch"}]'::jsonb,'slot kind cannot change');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Other","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":200}]'),'[{"code":"slot_block_mismatch"}]'::jsonb,'slot name pinned to catalog');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"nave","kind":"naturalScience","name":"NA","points":100},{"id":"iv1","kind":"individualChoice","name":"IV","points":200}]'),'[{"code":"unexpected_slot_block"}]'::jsonb,'foreign slot rejected');
select is(pg_temp.choice_diagnostics('[{"id":"Mosp","kind":"modernLanguage","name":"Moderna språk","points":200}]'),'[{"code":"invalid_choice_blocks"}]'::jsonb,'invalid stable id rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":" ","points":200}]'),'[{"code":"invalid_choice_blocks"}]'::jsonb,'blank name rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":200,"other":true}]'),'[{"code":"invalid_choice_blocks"}]'::jsonb,'extra block keys rejected');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":100},{"id":"iv2","kind":"individualChoice","name":"IV 2","points":100},{"id":"spec1","kind":"specialization","name":"Valbar fördjupning","points":100}]'),'[]'::jsonb,'split IV and own specialization block resolve');
select throws_ok($q$select public.phase5_programplan_term_rows(jsonb_set((select reference from sa_choice_basis limit 1),'{choiceBlocks}','[]'))$q$,'22023','Invalid programplan terms','invalid blocks cannot produce term rows');
select throws_ok($q$select public.phase5_programplan_choice_blocks(jsonb_set((select reference from sa_choice_basis limit 1),'{choiceBlocks}','[]'))$q$,'22023','Invalid programplan blocks','invalid blocks cannot resolve frames');
select lives_ok($q$select public.phase5_programplan_validate_basis((select reference from sa_choice_basis where reference->>'orientationCode'='SABEP'),jsonb_populate_record(null::public.offerings,'{"program_code":"SA25","orientation_code":"SABEP"}'))$q$,'v2 passes pinned offering validation');
select throws_ok($q$select public.phase5_programplan_validate_basis((select reference from sa_choice_basis where reference->>'orientationCode'='SABEP'),jsonb_populate_record(null::public.offerings,'{"program_code":"EK25","orientation_code":"EKEKI"}'))$q$,'22023','Invalid programplan basis','wrong offering pin rejected');
select throws_ok($q$select public.phase5_programplan_validate_basis((select reference from sa_choice_basis where reference->>'orientationCode'='SABEP'),jsonb_populate_record(null::public.offerings,'{"program_code":"SA25","orientation_code":"SABEP"}'),array['ENGE3000X'])$q$,'22023','Legacy choices mismatch','legacy specialization history still exact');
select ok(not exists(select 1 from pg_proc p cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a
 where p.pronamespace='public'::regnamespace and p.proname in ('phase5_programplan_choice_blocks','phase5_programplan_choice_block_diagnostics','phase5_programplan_alternative_groups')
 and a.grantee in (0,(select oid from pg_roles where rolname='anon'),(select oid from pg_roles where rolname='authenticated'),(select oid from pg_roles where rolname='skolplattform_worker'),(select oid from pg_roles where rolname='service_role')) and a.privilege_type='EXECUTE'),'all new internals closed to clients Worker and service role');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":200},{"id":"constructor","kind":"specialization","name":"Fördjupning","points":100}]'),'[]'::jsonb,'constructor custom id follows contract regex');
select is(pg_temp.choice_diagnostics('[{"id":"mosp","kind":"modernLanguage","name":"Moderna språk","points":200},{"id":"iv1","kind":"individualChoice","name":"IV","points":200},{"id":"prototype","kind":"specialization","name":"Fördjupning","points":100}]'),'[]'::jsonb,'prototype custom id follows contract regex');
select * from finish();
rollback;
