import artifact from './programplan-catalog.generated.json' with {type:'json'};
import {ProgramplanContractError,type ProgramplanCatalog,type ProgramplanLevelRef,type ProgramplanBasisReference,type CatalogProgram} from './programplan-catalog.ts';
import {programplanChoiceBlocks,type ProgramplanChoiceBlock} from './programplan-choice-blocks.ts';
import {programplanTermRows,type ProgramplanTermPoints} from './programplan-terms.ts';
import {PROGRAMPLAN_LANGUAGES,PROGRAMPLAN_LANGUAGE_LADDERS,type ProgramplanLanguageLadder} from './programplan-languages.ts';
export type ProgramplanLanguageRef = {type:'language';languageCode:string|null;levels:ProgramplanLevelRef[]};
/** Versioned generic package references open only in step D. */
export type ProgramplanPackageRef = ProgramplanLanguageRef;
export type ProgramplanPackageDistribution = {levelKey:string;points:ProgramplanTermPoints}[];
export type ProgramplanPackageEntry = {ref:ProgramplanPackageRef;distribution:ProgramplanPackageDistribution};
export type ProgramplanPackageSelection = {blockId:string;entries:ProgramplanPackageEntry[]};
export type ProgramplanUnitPackage = {unitId:string;revision:number;selections:ProgramplanPackageSelection[]};
export type ProgramplanUnitPackages = {planId:string;units:ProgramplanUnitPackage[]};
export type ProgramplanPackageReadRequest = {planId:string};
export type ProgramplanPackageWriteRequest = {planId:string;unitId:string;expectedRevision:number;blockId:string;entries:ProgramplanPackageEntry[]};
export type ProgramplanLanguageStart = {ladderId:string;startIndex:number;name:string;levels:ProgramplanLevelRef[]};
const defaultCatalog=artifact as ProgramplanCatalog;
function bad(code='invalid_programplan_packages'):never {throw new ProgramplanContractError(code);}
function shape(value:unknown,keys:string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))bad();const proto=Object.getPrototypeOf(value);if((proto!==Object.prototype&&proto!==null)||Object.getOwnPropertySymbols(value).length||Object.values(Object.getOwnPropertyDescriptors(value)).some(d=>d.get!==undefined||d.set!==undefined))bad();const row=value as Record<string,unknown>;if(keys.some(k=>!Object.hasOwn(row,k))||Object.getOwnPropertyNames(row).some(k=>!keys.includes(k)))bad();return row;}
function array(value:unknown,max:number):unknown[]{if(!Array.isArray(value)||value.length>max||Object.getPrototypeOf(value)!==Array.prototype||Object.getOwnPropertySymbols(value).length||Object.getOwnPropertyNames(value).length!==value.length+1||Object.values(Object.getOwnPropertyDescriptors(value)).some(d=>d.get!==undefined||d.set!==undefined))bad();for(let i=0;i<value.length;i++)if(!Object.hasOwn(value,i))bad();return value;}
function integer(value:unknown,max=2147483646,min=0):number{if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min||value>max)bad();return value;}
function uuid(value:unknown):string{if(typeof value!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value))bad();return value.toLowerCase();}
function blockId(value:unknown):string{if(typeof value!=='string'||! /^[a-z][a-z0-9]{0,15}$/u.test(value)||['constructor','prototype','__proto__'].includes(value))bad();return value;}
function code(value:unknown):string{if(typeof value!=='string'||value.length>96||! /^\p{L}[\p{L}\p{N}_-]*$/u.test(value)||['constructor','prototype','__proto__'].includes(value))bad();return value;}
export function programplanPackageLevelKey(level:ProgramplanLevelRef):string{return `${level.subjectCode}:${level.subjectVersion}:${level.itemCode}`;}
export function programplanPackageKey(ref:ProgramplanPackageRef):string{return `language:${ref.languageCode??'-'}:${ref.levels.map(l=>l.itemCode).join('+')}`;}
export const entryKey=programplanPackageKey;
export function programplanPackageLevelName(level:ProgramplanLevelRef,catalog:ProgramplanCatalog=defaultCatalog):string{const subject=catalog.subjects.find(s=>s.code===level.subjectCode&&s.version===level.subjectVersion),item=subject?.items.find(i=>i.code===level.itemCode&&i.points===level.points);return subject&&item?`${subject.name} – ${item.name}`:level.itemCode;}
function points(value:unknown):ProgramplanTermPoints{const values=array(value,6);if(values.length!==6)bad();return values.map(p=>integer(p,10000)) as ProgramplanTermPoints;}
function ladderOf(levels:ProgramplanLevelRef[]):{ladder:ProgramplanLanguageLadder;start:number}|null{for(const ladder of PROGRAMPLAN_LANGUAGE_LADDERS){const start=ladder.steps.findIndex(s=>s.subjectCode===levels[0]?.subjectCode&&s.itemCode===levels[0]?.itemCode);if(start>=0&&start+levels.length<=ladder.steps.length&&levels.every((l,i)=>l.subjectCode===ladder.steps[start+i].subjectCode&&l.itemCode===ladder.steps[start+i].itemCode))return{ladder,start};}return null;}
export function parseProgramplanLanguageRef(value:unknown):ProgramplanLanguageRef{if(value&&typeof value==='object'&&Object.getOwnPropertyDescriptor(value,'type')?.value==='package')bad('unsupported_programplan_package');const row=shape(value,['type','languageCode','levels']);if(row.type!=='language')bad();const levels=array(row.levels,7).map(l=>{const r=shape(l,['subjectCode','subjectVersion','itemCode','points']);return{subjectCode:code(r.subjectCode),subjectVersion:integer(r.subjectVersion,100000,1),itemCode:code(r.itemCode),points:integer(r.points,10000,1)};});if(!levels.length||new Set(levels.map(programplanPackageLevelKey)).size!==levels.length)bad();const found=ladderOf(levels);if(!found)bad();const languageCode=row.languageCode;if(found.ladder.languageRequired){if(typeof languageCode!=='string'||!PROGRAMPLAN_LANGUAGES.some(l=>l.code===languageCode)||(found.ladder.languageCode!==null&&languageCode!==found.ladder.languageCode))bad();}else if(languageCode!==null)bad();return{type:'language',languageCode:languageCode as string|null,levels};}
export function parseProgramplanPackageEntries(value:unknown):ProgramplanPackageEntry[]{const entries=array(value,200).map(e=>{const row=shape(e,['ref','distribution']);const ref=parseProgramplanLanguageRef(row.ref);const levels=new Map(ref.levels.map(l=>[programplanPackageLevelKey(l),l]));const distribution=array(row.distribution,200).map(d=>{const r=shape(d,['levelKey','points']);if(typeof r.levelKey!=='string'||!levels.has(r.levelKey))bad();const p=points(r.points);if(p.reduce((n,x)=>n+x,0)>levels.get(r.levelKey)!.points)bad();return{levelKey:r.levelKey,points:p};});if(new Set(distribution.map(d=>d.levelKey)).size!==distribution.length)bad();return{ref,distribution};});if(new Set(entries.map(e=>programplanPackageKey(e.ref))).size!==entries.length)bad();return entries;}
export function parseProgramplanPackageRead(value:unknown):ProgramplanPackageReadRequest{const r=shape(value,['planId']);return{planId:uuid(r.planId)};}
export function parseProgramplanPackageWrite(value:unknown):ProgramplanPackageWriteRequest{const r=shape(value,['planId','unitId','expectedRevision','blockId','entries']);return{planId:uuid(r.planId),unitId:uuid(r.unitId),expectedRevision:integer(r.expectedRevision),blockId:blockId(r.blockId),entries:parseProgramplanPackageEntries(r.entries)};}
export function parseProgramplanUnitPackages(value:unknown):ProgramplanUnitPackages{const r=shape(value,['planId','units']);const units=array(r.units,1000).map(u=>{const row=shape(u,['unitId','revision','selections']);const selections=array(row.selections,16).map(s=>{const x=shape(s,['blockId','entries']);return{blockId:blockId(x.blockId),entries:parseProgramplanPackageEntries(x.entries)};});if(new Set(selections.map(s=>s.blockId)).size!==selections.length)bad();const revision=integer(row.revision,2147483647);if(revision===0&&selections.length)bad();return{unitId:uuid(row.unitId),revision,selections};});if(new Set(units.map(u=>u.unitId)).size!==units.length)bad();return{planId:uuid(r.planId),units};}
export function programplanPackageLevels(ref:ProgramplanPackageRef,catalog:ProgramplanCatalog=defaultCatalog):ProgramplanLevelRef[]{const parsed=parseProgramplanLanguageRef(ref);return parsed.levels.map(level=>{const subjects=catalog.subjects.filter(s=>s.code===level.subjectCode&&s.version===level.subjectVersion);const item=subjects.length===1?subjects[0].items.find(l=>l.code===level.itemCode&&l.points===level.points):null;if(!item||!subjects[0].schoolTypes.includes('GY')||subjects[0].typeOfSyllabus!=='GRADE_SUBJECT_SYLLABUS')bad();return{...level};});}
function ladderLevels(ladder:ProgramplanLanguageLadder,start:number,count:number,catalog:ProgramplanCatalog):ProgramplanLevelRef[]{return ladder.steps.slice(start,start+count).map(step=>{const subjects=catalog.subjects.filter(s=>s.code===step.subjectCode&&s.schoolTypes.includes('GY'));if(subjects.length!==1)bad();const item=subjects[0].items.find(l=>l.code===step.itemCode);if(!item)bad();return{subjectCode:step.subjectCode,subjectVersion:subjects[0].version,itemCode:step.itemCode,points:item.points};});}
export function createLanguagePackage(languageCode:string|null,ladderId:string,startIndex:number,packagePoints:number,catalog:ProgramplanCatalog=defaultCatalog):ProgramplanLanguageRef{const ladder=PROGRAMPLAN_LANGUAGE_LADDERS.find(l=>l.id===ladderId);if(!ladder||!Number.isSafeInteger(startIndex)||startIndex<0||!Number.isSafeInteger(packagePoints)||packagePoints<100||packagePoints%100!==0||startIndex+packagePoints/100>ladder.steps.length)bad();const levels=ladderLevels(ladder,startIndex,packagePoints/100,catalog);if(levels.reduce((n,l)=>n+l.points,0)!==packagePoints)bad();return parseProgramplanLanguageRef({type:'language',languageCode,levels});}
export function languagePackageStartOptions(block:Pick<ProgramplanChoiceBlock,'kind'|'points'>,catalog:ProgramplanCatalog=defaultCatalog):ProgramplanLanguageStart[]{if(block.kind==='naturalScience'||!Number.isSafeInteger(block.points)||block.points%100!==0||block.points<100)return[];const result:ProgramplanLanguageStart[]=[];for(const ladder of PROGRAMPLAN_LANGUAGE_LADDERS)for(let i=0;i+block.points/100<=ladder.steps.length;i++){try{const levels=ladderLevels(ladder,i,block.points/100,catalog);if(levels.reduce((n,l)=>n+l.points,0)===block.points)result.push({ladderId:ladder.id,startIndex:i,name:levels.map(l=>programplanPackageLevelName(l,catalog)).join(' → '),levels});}catch{/* Only starts present in the pinned catalog are offered. */}}return result;}
export function proposeLanguagePackages(block:Pick<ProgramplanChoiceBlock,'kind'|'points'>,catalog:ProgramplanCatalog=defaultCatalog):ProgramplanPackageEntry[]{if(block.kind!=='modernLanguage')return[];return ['fr','es','de'].flatMap(languageCode=>[2,0].map(start=>({ref:createLanguagePackage(languageCode,'modern',start,block.points,catalog),distribution:[]})));}
export function suggestPackageDistribution(frame:ProgramplanTermPoints,levels:ProgramplanLevelRef[]):ProgramplanPackageDistribution{const remaining=[...points(frame)];return levels.map(l=>{let unallocated=integer(l.points,10000,1);const p:ProgramplanTermPoints=[0,0,0,0,0,0];for(let i=0;i<6;i++){p[i]=Math.min(unallocated,remaining[i]);remaining[i]-=p[i];unallocated-=p[i];}return{levelKey:programplanPackageLevelKey(l),points:p};});}
/** Content validity is strict; incomplete/out-of-frame term choices remain saveable and diagnosable. */
export function validateProgramplanPackageEntries(program:CatalogProgram,basis:ProgramplanBasisReference,block:string,entries:unknown,catalog:ProgramplanCatalog=defaultCatalog):ProgramplanPackageEntry[]{const parsed=parseProgramplanPackageEntries(entries);const choice=programplanChoiceBlocks(program,basis).find(b=>b.id===block);if(!choice||basis.catalogId!==catalog.catalogId||program.code!==basis.programRef.code||program.version!==basis.programRef.version)bad();const fixed=new Set(programplanTermRows(program,basis).flatMap(r=>r.key.startsWith('alternative:')?r.key.split(':').slice(2).join(':').split('+'):r.key.startsWith('block:')||r.key.startsWith('meta:')?[]:[r.key.split(':').slice(1).join(':')]));for(const entry of parsed){const levels=programplanPackageLevels(entry.ref,catalog);if(choice.kind==='naturalScience'||levels.reduce((n,l)=>n+l.points,0)!==choice.points)bad();for(const level of levels){const subject=catalog.subjects.find(s=>s.code===level.subjectCode&&s.version===level.subjectVersion)!;if(!subject.startDate||basis.startedOn<subject.startDate||(subject.endDate!==null&&basis.startedOn>subject.endDate)||(subject.canceledDate!==null&&basis.startedOn>=subject.canceledDate)||fixed.has(programplanPackageLevelKey(level)))bad();if(choice.kind==='specialization'&&!program.specialization.some(s=>s.code===level.subjectCode&&s.subjectVersion===level.subjectVersion&&s.levels.some(l=>l.code===level.itemCode&&l.points===level.points)))bad();}}return parsed;}
