import test from 'node:test';
import assert from 'node:assert/strict';
import catalog from './programplan-catalog.generated.json' with {type:'json'};
import {defaultProgramplanChoiceBlocks} from './programplan-choice-blocks.ts';
import {proposeLanguagePackages,createLanguagePackage,programplanPackageKey,programplanPackageLevelKey,suggestPackageDistribution,parseProgramplanPackageWrite,parseProgramplanUnitPackages,validateProgramplanPackageEntries} from './programplan-packages.ts';
const id='55002300-0000-4000-8000-000000000001',unit='55002300-0000-4000-8000-000000000002';
function context(code='SA25'){const program=catalog.programs.find(p=>p.code===code);const basis={catalogId:catalog.catalogId,programRef:{code,version:program.version},orientationCode:program.orientations[0]?.code??null,startedOn:'2027-08-15',specializationRefs:[],choiceBlocks:defaultProgramplanChoiceBlocks(program,program.orientations[0]?.code??null)};return{program,basis,block:basis.choiceBlocks.find(b=>b.kind==='modernLanguage')};}
test('six proposals use block points, correct consecutive starts and distinct value keys',()=>{for(const [code,count] of [['EK25',1],['NA25',1],['SA25',2],['HU25',2],['SM25',3]]){const {block}=context(code),entries=proposeLanguagePackages(block);assert.equal(entries.length,6);assert.equal(new Set(entries.map(x=>programplanPackageKey(x.ref))).size,6);for(const e of entries){assert.equal(e.ref.levels.length,count);assert.equal(e.ref.levels.reduce((n,l)=>n+l.points,0),block.points);assert.deepEqual(e.distribution,[]);}assert.deepEqual(entries[0].ref.levels.map(l=>l.itemCode),['MODO1000X','MODO2000X','MODF1000X'].slice(0,count));assert.deepEqual(entries[1].ref.levels.map(l=>l.itemCode),['MODY1000X','MODG1000X','MODO1000X'].slice(0,count));}});
test('ladder permits continuation 2 to advanced 1, sign and minority, rejects gaps, unknown code, false version, fixed level and wrong frame points',()=>{const {program,basis}=context(),ref=createLanguagePackage('de','modern',3,200);assert.deepEqual(ref.levels.map(l=>l.itemCode),['MODO2000X','MODF1000X']);const entry={ref,distribution:[]};assert.equal(validateProgramplanPackageEntries(program,basis,'mosp',[entry],catalog).length,1);for(const mutate of [e=>e.ref.languageCode='xx',e=>e.ref.levels[1].itemCode='MODF2000X',e=>e.ref.levels[0].subjectVersion=2,e=>e.ref.levels.pop()]){const e=structuredClone(entry);mutate(e);assert.throws(()=>validateProgramplanPackageEntries(program,basis,'mosp',[e],catalog));}assert.throws(()=>createLanguagePackage('fr','sign',0,200));assert.throws(()=>createLanguagePackage(null,'modern',0,200));assert.throws(()=>createLanguagePackage('de','FINX',0,200));const fi=createLanguagePackage('fi','FINX',0,200);validateProgramplanPackageEntries(program,basis,'mosp',[{ref:fi,distribution:[]}],catalog);const sign=createLanguagePackage(null,'sign',0,200);validateProgramplanPackageEntries(program,basis,'mosp',[{ref:sign,distribution:[]}],catalog);const clone=structuredClone(basis);clone.specializationRefs=[ref.levels[0]];assert.throws(()=>validateProgramplanPackageEntries(program,clone,'mosp',[entry],catalog));});
test('distribution walks the frame in order, preserves integers and allows unfinished frame',()=>{const ref=createLanguagePackage('fr','modern',2,200);const frame=[50,50,50,50,0,0];const d=suggestPackageDistribution(frame,ref.levels);assert.deepEqual(d.map(x=>x.points),[[50,50,0,0,0,0],[0,0,50,50,0,0]]);assert.deepEqual(frame,[50,50,50,50,0,0]);assert.deepEqual(suggestPackageDistribution([0,50,0,0,0,0],ref.levels).map(x=>x.points),[[0,50,0,0,0,0],[0,0,0,0,0,0]]);assert.throws(()=>suggestPackageDistribution([1.5,0,0,0,0,0],ref.levels));});
test('strict request/result parser rejects extras, sparse arrays, getters, duplicated ids/rows, oversized points and future package refs',()=>{const entry=proposeLanguagePackages(context().block)[0],body={planId:id,unitId:unit,expectedRevision:0,blockId:'mosp',entries:[entry]};assert.deepEqual(parseProgramplanPackageWrite(body),body);const result={planId:id,units:[{unitId:unit,revision:1,selections:[{blockId:'mosp',entries:[entry]}]}]};assert.deepEqual(parseProgramplanUnitPackages(result),result);for(const mutate of [x=>x.actorId=id,x=>x.entries=[...x.entries,...x.entries],x=>x.entries[0].ref.languageCode='XX',x=>x.entries[0].ref={type:'package',packageId:id,version:1},x=>x.entries[0].distribution=[{levelKey:programplanPackageLevelKey(entry.ref.levels[0]),points:[101,0,0,0,0,0]}]]){const b=structuredClone(body);mutate(b);assert.throws(()=>parseProgramplanPackageWrite(b));}const sparse=Array(1);assert.throws(()=>parseProgramplanPackageWrite({...body,entries:sparse}));const accessor={};Object.defineProperty(accessor,'type',{get(){throw Error('getter executed');},enumerable:true});assert.throws(()=>parseProgramplanPackageWrite({...body,entries:[{ref:accessor,distribution:[]}]}),e=>e.code==='invalid_programplan_packages');assert.throws(()=>parseProgramplanUnitPackages({...result,units:[...result.units,...result.units]}));});
test('valid imperfect distribution stays saveable for analysis, but orphan and excessive level allocation do not',()=>{const {program,basis,block}=context(),entry=proposeLanguagePackages(block)[0];entry.distribution=entry.ref.levels.map(l=>({levelKey:programplanPackageLevelKey(l),points:[0,0,0,0,0,100]}));assert.equal(validateProgramplanPackageEntries(program,basis,'mosp',[entry],catalog).length,1);entry.distribution[0].points[5]=101;assert.throws(()=>validateProgramplanPackageEntries(program,basis,'mosp',[entry],catalog));entry.distribution[0]={levelKey:'OTHER:1:OTHER1000X',points:[0,0,0,0,0,0]};assert.throws(()=>validateProgramplanPackageEntries(program,basis,'mosp',[entry],catalog));});
