import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { registerHooks } from 'node:module';
const id='55101000-0000-4000-8000-000000000001', unit='55101000-0000-4000-8000-000000000002';
const issuer='http://host.docker.internal:8180/realms/skolplattform-test',clientId='skolplattform-worker';
const artifact=JSON.parse(await readFile(new URL('../programplan-catalog.generated.json',import.meta.url),'utf8'));
let state;
const fixture=globalThis.__programplanWorkspaceTest={
 env:{APP_MODE:'protected',DATABASE_URL:'postgres://synthetic@127.0.0.1:56322/postgres',SUPABASE_URL:'http://127.0.0.1:56321',OIDC_ISSUER:issuer,OIDC_CLIENT_ID:clientId,MFA_MAX_AGE_SECONDS:'28800',SESSION_SECRET:'synthetic-workspace-only'},
 session(){const future=new Date(Date.now()+60000);return{session:{id,identityId:id,membershipId:id,assignmentId:id,customerId:id,expiresAt:future,absoluteExpiresAt:future,epoch:1}};},
 async login(_corr,fn){return fn(fixture.tx);},
 async context(_ctx,fn){const eventCount=state.events.length;try{return await fn(fixture.tx,{sessionId:id,identityId:id,membershipId:id,assignmentId:id,customerId:id,identity:{issuer,subject:'synthetic'},correlationId:id,accessFunction:state.fn,epoch:1,mfa:{issuer,clientId,audience:[clientId],profileId:'local-keycloak-admin',profileVersion:1,acr:'1',amr:['pwd'],authTime:new Date(Date.now()-1000),checkedAt:new Date()}});}catch(error){state.events.length=eventCount;throw error;}},
 tx:async(strings,...values)=>{const sql=strings.join('?');if(sql.includes('select i.auth_user_id'))return[{function:state.fn}];if(sql.includes('insert into public.security_events')){if(state.auditFails)throw new Error('private audit content');state.events.push({action:values[8],objectType:values[9],objectId:values[10],outcome:values[11],details:values[12]});return[];}state.calls.push({sql,values});if(state.sqlError)throw state.sqlError;return[{result:state.result}];},
};fixture.tx.json=value=>value;
registerHooks({load(url,context,next){let source;if(url===new URL('./db.ts',import.meta.url).href)source=`export class Deny extends Error{constructor(code,status=403,details){super(code);this.code=code;this.status=status;this.details=details;}}export const withLoginPhase=(...a)=>globalThis.__programplanWorkspaceTest.login(...a);export const withSessionContext=(...a)=>globalThis.__programplanWorkspaceTest.context(...a);`;if(url===new URL('./session.ts',import.meta.url).href)source='export const readSession=async()=>globalThis.__programplanWorkspaceTest.session();';if(url===new URL('./env.ts',import.meta.url).href)source='export const serverEnv=()=>globalThis.__programplanWorkspaceTest.env;';return source?{format:'module',source,shortCircuit:true}:next(url,context);}});
const {POST:list}=await import('../../app/api/programplaner/lista/route.ts');
const {POST:underlag}=await import('../../app/api/programplaner/underlag/route.ts');
const routes={lista:list,underlag};
const education=()=>({id,unitId:unit,schoolName:'Syntetisk skola',kind:'gymnasium',name:'Syntetisk ES',localCode:null,cohort:'Fri kulltext',startYear:null,status:'planerad',programCode:'ES25',orientationCode:'ESBIF',latestVersion:0,draftId:null});
const lifecycle=()=>({phase:'framtida',startsOn:null,archived:false,revision:0,units:[{id:unit,name:'Syntetisk skola',primary:true,inMandate:true}]});
const workspace=()=>({education:education(),lifecycle:lifecycle(),versions:[],versionCount:0,versionPage:1,pageSize:50,catalogs:[{catalogId:artifact.catalogId,source:artifact.source}],catalog:{status:'unselected',catalogId:null,diagnostic:null,payload:null},decisionReady:false});
function reset(route='underlag'){state={fn:'rektor',result:route==='lista'?{offerings:[{...education(),lifecycle:lifecycle()}],count:1,page:1,pageSize:50}:workspace(),calls:[],events:[]};}
function request(route,body=route==='lista'?{page:1}:{offeringId:id,versionPage:1,catalogId:null},origin='http://localhost'){return new Request(`http://localhost/api/programplaner/${route}`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Context-Epoch':'1'},body:JSON.stringify(body)});}
for(const name of Object.keys(routes))test(`${name}: HM/rektor reads without MFA through one parameterized operation and minimal audit`,async()=>{
 for(const fn of ['huvudman','rektor']){reset(name);state.fn=fn;const response=await routes[name](request(name));assert.equal(response.status,200);const body=await response.json();assert.equal(response.headers.get('cache-control'),'no-store');assert.equal(state.calls.length,1);assert.equal(state.events.length,1);assert.equal(state.events[0].action,name==='lista'?'programplan_offerings_listed':'programplan_workspace_read');assert.equal(state.events[0].objectType,name==='lista'?'education_collection':'education');assert.equal(state.events[0].objectId,name==='lista'?null:id);assert.deepEqual(state.events[0].details,{accessFunction:fn});if(name==='underlag'){assert.equal(body.catalog.status,'unselected');assert.equal(body.education.startYear,null);assert.equal(body.decisionReady,false);}else assert.equal(body.offerings[0].latestVersion,0);}
});
for(const name of Object.keys(routes))test(`${name}: denied role, stale context, malformed shape and audit failures return no protected data`,async()=>{
 for(const fn of ['administrator','larare','support','it','kundadmin','elevhalsa','granskare']){reset(name);state.fn=fn;const response=await routes[name](request(name));assert.equal(response.status,403);assert.equal(state.calls.length,0);}
 reset(name);const stale=request(name);stale.headers.set('X-Context-Epoch','2');assert.equal((await routes[name](stale)).status,409);assert.equal(state.calls.length,0);
 reset(name);const foreign=request(name,undefined,'https://foreign.test');assert.equal((await routes[name](foreign)).status,403);assert.equal(state.calls.length,0);
 reset(name);const body=name==='lista'?{page:1,actorId:id}:{offeringId:id,versionPage:1,catalogId:null,startedOn:'2026-08-01'};assert.equal((await routes[name](request(name,body))).status,400);assert.equal(state.calls.length,0);
 for(const[code,status]of[['42501',403],['22023',400],['55000',500]]){reset(name);state.sqlError={code,message:'private SQL'};const response=await routes[name](request(name));assert.equal(response.status,status);assert.equal(JSON.stringify(await response.json()).includes('private'),false);}
 reset(name);state.result.private='private result';const malformed=await routes[name](request(name));assert.equal(malformed.status,500);assert.equal((await malformed.json()).code,'audit_unavailable');assert.equal(state.events.filter(e=>e.outcome==='ok').length,0);
 reset(name);state.auditFails=true;const failed=await routes[name](request(name));assert.equal(failed.status,500);assert.equal((await failed.json()).code,'audit_unavailable');assert.equal(state.events.filter(e=>e.outcome==='ok').length,0);
});
test('whole stored artifact is hashed before returning a smaller source projection; no latest fallback',async()=>{
 reset();const{catalogId,...payload}=structuredClone(artifact);state.result.catalog={status:'selected',catalogId,diagnostic:null,payload};
 const response=await underlag(request('underlag',{offeringId:id,versionPage:1,catalogId}));assert.equal(response.status,200);const body=await response.json();assert.equal(body.catalog.catalogId,catalogId);assert.equal(body.catalog.program.code,'ES25');assert.deepEqual(body.catalog.program,artifact.programs.find(p=>p.code==='ES25'));assert.ok(body.catalog.subjects.length<artifact.subjects.length);assert.equal('payload'in body.catalog,false);assert.equal(body.decisionReady,false);assert.deepEqual(state.calls[0].values,[id,1,catalogId]);
 for(const mutate of [p=>p.programs[0].name='tampered while ID unchanged',p=>p.catalogId=catalogId,p=>p.private='hidden']){reset();const{catalogId:selectedId,...whole}=structuredClone(artifact);mutate(whole);state.result.catalog={status:'selected',catalogId:selectedId,diagnostic:null,payload:whole};const denied=await underlag(request('underlag',{offeringId:id,versionPage:1,catalogId:selectedId}));assert.equal(denied.status,500);assert.equal((await denied.json()).code,'audit_unavailable');assert.equal(state.events.filter(e=>e.outcome==='ok').length,0);}
});
test('explicit missing catalog and absent program/orientation remain readable source limitations',async()=>{
 const missing='sha256:'+'0'.repeat(64);reset();state.result.catalog={status:'blocked',catalogId:missing,diagnostic:'catalog_unavailable',payload:null};let response=await underlag(request('underlag',{offeringId:id,versionPage:1,catalogId:missing}));assert.equal(response.status,200);assert.equal((await response.json()).catalog.diagnostic,'catalog_unavailable');assert.equal(state.events.length,1);
 for(const[programCode,orientationCode,diagnostic]of[['UNKNOWN',null,'program_not_found'],['ES25','UNKNOWN','orientation_not_found'],['ES25',null,'orientation_required']]){reset();const{catalogId,...payload}=artifact;state.result.education.programCode=programCode;state.result.education.orientationCode=orientationCode;state.result.catalog={status:'selected',catalogId,diagnostic:null,payload};response=await underlag(request('underlag',{offeringId:id,versionPage:1,catalogId}));assert.equal(response.status,200);const body=await response.json();assert.equal(body.catalog.diagnostic,diagnostic);assert.equal(body.catalog.program,null);assert.equal(state.events.length,1);}
});
test('unknown ordered legacy codes and max/draft outside the current page survive without repair',async()=>{
 reset();state.result.education.latestVersion=52;state.result.education.draftId=unit;state.result.versionCount=52;state.result.versionPage=2;
 state.result.versions=[{id,version:2,revision:0,status:'ersatt',decidedOn:'2026-01-01',catalogId:null,basisReference:null,legacySpecialization:['UNKNOWN','FOTO1000X','UNKNOWN']},{id:unit,version:1,revision:0,status:'faststalld',decidedOn:'2025-01-01',catalogId:null,basisReference:null,legacySpecialization:[]}];
 // A hidden newer draft has its own ID, never the shown locked legacy version.
 state.result.education.draftId='55101000-0000-4000-8000-000000000005';
 const response=await underlag(request('underlag',{offeringId:id,versionPage:2,catalogId:null}));assert.equal(response.status,200);const body=await response.json();assert.deepEqual(body.versions[0].legacySpecialization,['UNKNOWN','FOTO1000X','UNKNOWN']);assert.equal(body.education.latestVersion,52);assert.equal(body.education.startYear,null);assert.equal(body.versions[0].basisReference,null);
});
