import test from 'node:test';
import assert from 'node:assert/strict';
import {REQUIRED_CASES,PROGRAMPLAN_ENTRIES,TIMPLAN_ENTRIES,WORKSPACE_ENTRIES,parseArgs,overallStatus,exactFunctions,withTemporaryGrants} from './verify-programplan-api.mjs';
const pass=name=>({name,status:'PASS',checks:[{kind:'response',ok:true},{kind:'persistent',ok:true}]});
test('full unik matris kräver svar och beständig evidens utan skip',()=>{assert.equal(overallStatus(REQUIRED_CASES.map(pass)),'PASS');assert.equal(overallStatus(REQUIRED_CASES.slice(1).map(pass)),'FAIL');assert.equal(overallStatus([...REQUIRED_CASES.map(pass),pass(REQUIRED_CASES[0])]),'FAIL');assert.equal(overallStatus(REQUIRED_CASES.map(name=>({...pass(name),checks:[{kind:'response',ok:true}]}))),'FAIL');assert.equal(overallStatus(REQUIRED_CASES.map(name=>({...pass(name),status:'SKIP'}))),'FAIL');});
test('importsäkert målskydd och stängda åtta signaturer, aldrig nionde helper',()=>{for(const args of[[],['--target','baseline'],['--target','protected','--out','report.json'],['--target','protected','--out','/tmp/p509.json','--port','80'],['--target','protected','--out','/tmp/p509.json','--linked']])assert.throws(()=>parseArgs(args));assert.equal(parseArgs(['--target','protected','--out','/tmp/p509.json','--preflight']).preflight,true);const all=[...TIMPLAN_ENTRIES,...PROGRAMPLAN_ENTRIES];assert.equal(exactFunctions(all,all),true);assert.equal(exactFunctions([...all,'public.phase5_programplan_result(uuid)'],all),false);assert.equal(exactFunctions([...all.slice(1),all[1]],all),false);});
test('delvis grant eller provfel återställer ACL; återställningsfel kan aldrig ge PASS',async()=>{for(const failAt of['grant','run',null]){const trace=[];const before={acl:'closed'};const task=()=>withTemporaryGrants(before,async()=>{trace.push('grant');if(failAt==='grant')throw Error('grant');},async original=>{assert.equal(original,before);trace.push('restore');},async()=>{trace.push('verify');return true;},async()=>{trace.push('run');if(failAt==='run')throw Error('run');return 'PASS';});if(failAt)await assert.rejects(task);else assert.equal(await task(),'PASS');assert.deepEqual(trace.slice(-2),['restore','verify']);}await assert.rejects(()=>withTemporaryGrants({},async()=>{},async()=>{},async()=>false,async()=>'PASS'),/acl_restore_failed/);});

test('workspace profile requires exactly ten entries and cannot preflight historical grants',()=>{const base=[...TIMPLAN_ENTRIES,...PROGRAMPLAN_ENTRIES],all=[...base,...WORKSPACE_ENTRIES];assert.equal(parseArgs(['--target','protected','--out','/tmp/p510.json','--workspace']).workspace,true);assert.throws(()=>parseArgs(['--target','protected','--out','/tmp/p510.json','--workspace','--preflight']));assert.equal(exactFunctions(all,all),true);assert.equal(exactFunctions(base,all),false);assert.equal(exactFunctions([...all,'public.phase5_programplan_workspace_audit(uuid,text)'],all),false);});
