import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {BLOCK_STEP_D_CASES,PACKAGE_BUSINESS_TABLES,blockStepDStatus,packageWorkerInventory} from './verify-programplan-choice-packages-api.mjs';
import {PACKAGE_ENTRIES,exactFunctions} from './verify-programplan-api.mjs';
import {parseBlockApiArgs} from './verify-programplan-blocks-api.mjs';
import {parseApplyArgs,verifyPreflight} from './apply-programplan-migration.mjs';
const cases=()=>BLOCK_STEP_D_CASES.map(name=>({name,status:'PASS',checks:[{name:'executed actual behavior',ok:true}]}));
const paths=['work/pilot/verify-programplan-choice-packages-api.mjs','work/pilot/verify-programplan-api.mjs','work/pilot/apply-programplan-migration.mjs','web/lib/programplan-packages.ts','web/lib/server/programplan-packages.ts','web/lib/server/audit-details.ts','web/app/api/programplaner/valpaket/route.ts','web/app/api/programplaner/valpaket/lista/route.ts','web/app/protected-programplan-package-dialog.tsx','supabase/migrations/20261004156000_phase5_programplan_packages.sql','supabase/migrations/20261004157000_phase5_worker_programplan_packages.sql'];
const hash=createHash('sha256').update('source').digest('hex');
function proof(){const hashes=Object.fromEntries(PACKAGE_BUSINESS_TABLES.map(t=>[t,{count:0,hash:'hash'}]));return{kind:'phase5-programplan-blocks-api',step:'d',target:'protected',scope:'local-synthetic-only',status:'PASS',preflight:true,preflightAclRestored:true,cleanupStatus:'PASS',originalBusinessPreserved:true,complete:true,aclUnchanged:true,cases:cases(),beforeWorkerFunctions:packageWorkerInventory(),verifiedWorkerFunctions:[...packageWorkerInventory(),...PACKAGE_ENTRIES],restoredWorkerFunctions:packageWorkerInventory(),libraryCleanup:{remainingOwnPackages:0},originalHashes:hashes,finalHashes:structuredClone(hashes),sourceCommit:'a'.repeat(40),workerBuildRevision:'b'.repeat(40),sourceHashes:Object.fromEntries(paths.map(p=>[p,hash]))};}
const verify=p=>verifyPreflight(p,()=>Buffer.from('source'),'phase5-programplan-blocks-api','d');
test('D routes its own eleven-case evidence and local output',()=>{const o=parseBlockApiArgs(['--step','d','--preflight']);assert.equal(o.step,'d');assert.equal(o.preflight,true);assert.match(o.outFile,/phase5-23-d-api.json$/);assert.throws(()=>parseBlockApiArgs(['--step','d','--base-url','https://example.com']),/unsafe/);});
test('D extends exact nineteen grants by exactly two and snapshots twelve whole tables',()=>{assert.equal(packageWorkerInventory().length,19);assert.equal(PACKAGE_ENTRIES.length,2);assert.equal(new Set([...packageWorkerInventory(),...PACKAGE_ENTRIES]).size,21);assert.equal(PACKAGE_BUSINESS_TABLES.length,12);assert(PACKAGE_BUSINESS_TABLES.includes('programplan_packages'));assert(!exactFunctions([...packageWorkerInventory(),PACKAGE_ENTRIES[0]],[...packageWorkerInventory(),...PACKAGE_ENTRIES]));});
test('D cannot pass on missing, duplicate, empty or failed behavior evidence',()=>{assert.equal(blockStepDStatus(cases()),'PASS');for(const mutate of [c=>c.pop(),c=>c.push(c[0]),c=>c[0].status='FAIL',c=>c[0].checks=[],c=>c[0].checks[0].ok=false]){const c=cases();mutate(c);assert.equal(blockStepDStatus(c),'FAIL');}});
test('D foundation cannot accept grants and grant migration requires preflight',()=>{assert.deepEqual(parseApplyArgs(['--migration','20261004156000_phase5_programplan_packages.sql']),{migration:'20261004156000_phase5_programplan_packages.sql',grants:null});assert.throws(()=>parseApplyArgs(['--migration','20261004156000_phase5_programplan_packages.sql','--grants','proof.json']),/not allowed/);assert.throws(()=>parseApplyArgs(['--migration','20261004157000_phase5_worker_programplan_packages.sql']),/required/);assert.equal(parseApplyArgs(['--migration','20261004157000_phase5_worker_programplan_packages.sql','--grants','proof.json']).grants,'proof.json');});
test('complete D preflight passes while mismatched stages, grants, cleanup, graph and sources fail closed',()=>{assert.doesNotThrow(()=>verify(proof()));for(const mutate of [p=>p.step='c',p=>p.target='remote',p=>p.cases.pop(),p=>p.cases[0].checks=[],p=>p.preflightAclRestored=false,p=>p.restoredWorkerFunctions.push(PACKAGE_ENTRIES[0]),p=>p.verifiedWorkerFunctions.pop(),p=>p.libraryCleanup.remainingOwnPackages=1,p=>p.finalHashes.point_plans.count=1,p=>delete p.originalHashes.programplan_packages,p=>p.sourceCommit='not-sha',p=>delete p.sourceHashes[paths[0]],p=>p.sourceHashes[paths[0]]='changed']){const p=proof();mutate(p);assert.throws(()=>verify(p),/REFUSED/);}});
