'use client';

import {useEffect,useRef,useState} from 'react';
import {api,ApiError} from '@/lib/server-client.ts';
import {useUnsavedChanges,confirmDiscard} from '@/lib/unsaved-changes.tsx';
import {type ProgramplanChoiceBlock} from '@/lib/programplan-choice-blocks.ts';
import {type ProgramplanTermPoints,PROGRAMPLAN_TERMS} from '@/lib/programplan-terms.ts';
import {PROGRAMPLAN_LANGUAGES,PROGRAMPLAN_LANGUAGE_LADDERS,programplanLanguageName} from '@/lib/programplan-languages.ts';
import {programplanPackageLevels,resolveProgramplanValpaket,createLanguagePackage,languagePackageStartOptions,parseProgramplanUnitPackages,proposeLanguagePackages,programplanPackageKey,programplanPackageLevelKey,programplanPackageLevelName,suggestPackageDistribution,
  type ProgramplanValpaket,type ProgramplanValpaketList,type ProgramplanPackageEntry,type ProgramplanUnitPackages} from '@/lib/programplan-packages.ts';
import artifact from '@/lib/programplan-catalog.generated.json';
import type {PlanIssue} from '@/lib/programplan-analysis.ts';
import type {ProgramplanOption} from '@/lib/protected-programplan.ts';
import ProgramplanPackageDialog from './protected-programplan-package-dialog';
import MfaStepUpNotice from './mfa-step-up';

export type SchoolPackagesProps={planId:string;scope:string;units:{id:string;name:string;inMandate:boolean}[];packages:ProgramplanUnitPackages|null;
  role:string;startedOn:string;valpaket:ProgramplanValpaketList[]|null;onValpaket:(value:ProgramplanValpaketList)=>void;packageError:string|null;archived:boolean;disabled:boolean;onPackages:(value:ProgramplanUnitPackages)=>void;onSecurityFailure:(error:unknown)=>boolean;onReadPackages:()=>Promise<void>};
const EMPTY:ProgramplanPackageEntry[]=[];
const zero=():ProgramplanTermPoints=>[0,0,0,0,0,0];
const equal=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
export default function ProgramplanPackageBlock({block,frame,focusIssue,selectedYear,options,fixedLevelKeys=[],...props}:SchoolPackagesProps&{block:ProgramplanChoiceBlock;frame:ProgramplanTermPoints;selectedYear:number;options:ProgramplanOption[];fixedLevelKeys?:string[];focusIssue?:PlanIssue|null}){
  const handledFocus=useRef<PlanIssue|null>(null);
  const initialUnit=props.units.find(u=>u.inMandate)?.id??props.units[0]?.id??'';
  const initialEntries=props.packages?.units.find(u=>u.unitId===initialUnit)?.selections.find(s=>s.blockId===block.id)?.entries??EMPTY;
  const [unitId,setUnitId]=useState(initialUnit),[entries,setEntries]=useState<ProgramplanPackageEntry[]>(initialEntries),[proposal,setProposal]=useState(false);
  const [message,setMessage]=useState<string|null>(null),[state,setState]=useState<'idle'|'saving'|'conflict'|'unknown'|'error'|'mfa'>('idle');
  const [reloading,setReloading]=useState(false);
  const [selectedPackage,setSelectedPackage]=useState(''),[dialog,setDialog]=useState<{source:ProgramplanValpaket|null}|null>(null);
  const [language,setLanguage]=useState('fr'),[start,setStart]=useState('modern:2');
  const starts=languagePackageStartOptions(block).filter(s=>s.levels.every(l=>!fixedLevelKeys.includes(programplanPackageLevelKey(l))&&(block.kind!=='specialization'||options.some(o=>o.subjectCode===l.subjectCode&&o.subjectVersion===l.subjectVersion&&o.itemCode===l.itemCode&&o.points===l.points)))), selectedStart=starts.find(s=>`${s.ladderId}:${s.startIndex}`===start)??starts[0];
  const library=props.valpaket?.find(list=>list.unitId===unitId)?.packages??[];
  const packageContext={unitId,packages:library};
  function levelsOf(ref:ProgramplanPackageEntry['ref']){try{return programplanPackageLevels(ref,undefined,packageContext);}catch{return [];}}
  function packageOf(ref:ProgramplanPackageEntry['ref']){try{return ref.type==='package'?resolveProgramplanValpaket(ref,packageContext):null;}catch{return null;}}
  const offered=library.filter(p=>p.kind===block.kind&&p.points===block.points&&p.levels.every(l=>{const subject=artifact.subjects.find(s=>s.code===l.subjectCode&&s.version===l.subjectVersion);return!!subject?.startDate&&props.startedOn>=subject.startDate&&(!subject.endDate||props.startedOn<=subject.endDate)&&(!subject.canceledDate||props.startedOn<subject.canceledDate)&&!fixedLevelKeys.includes(programplanPackageLevelKey(l))&&(block.kind!=='specialization'||options.some(o=>o.subjectCode===l.subjectCode&&o.subjectVersion===l.subjectVersion&&o.itemCode===l.itemCode&&o.points===l.points));}));
  const chosen=offered.find(p=>`${p.packageId}@${p.version}`===selectedPackage)??offered[0];
  function addGeneric(){if(!chosen)return;const ref={type:'package' as const,packageId:chosen.packageId,version:chosen.version};if(entries.some(e=>programplanPackageKey(e.ref)===programplanPackageKey(ref))){setMessage('Paketet finns redan.');return;}update([...entries,{ref,distribution:suggestPackageDistribution(frame,chosen.levels)}],true);}
  function latest(pack:ProgramplanValpaket){return library.filter(p=>p.packageId===pack.packageId).sort((a,b)=>b.version-a.version)[0]??pack;}
  function canVersion(pack:ProgramplanValpaket){const source=latest(pack);return props.role==='huvudman'||!!source.unitId&&!!props.units.find(u=>u.id===source.unitId&&u.inMandate);}
  const unit=props.units.find(u=>u.id===unitId), saved=props.packages?.units.find(u=>u.unitId===unitId);
  const savedEntries=saved?.selections.find(s=>s.blockId===block.id)?.entries??EMPTY;
  const valuesRef=useRef(entries),baseRef=useRef(savedEntries),propsRef=useRef(props),busy=useRef(false),queued=useRef(false),mounted=useRef(true),stateRef=useRef(state);
  useEffect(()=>{propsRef.current=props;},[props]);
  function transition(next:typeof state){stateRef.current=next;setState(next);}
  const dirty=!proposal&&!equal(entries,savedEntries);
  const writable=!!unit?.inMandate&&!props.archived&&!props.disabled;
  const locked=!writable||reloading||['conflict','unknown','mfa'].includes(state)||!saved;
  useUnsavedChanges(`packages-${props.scope}-${props.planId}-${unitId}-${block.id}`,dirty||state==='saving');
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  useEffect(()=>{
    if(busy.current||!equal(valuesRef.current,baseRef.current))return;
    baseRef.current=savedEntries;valuesRef.current=savedEntries;setEntries(savedEntries);setProposal(false);
  },[savedEntries]);
  function update(next:ProgramplanPackageEntry[],commit=false){valuesRef.current=next;setEntries(next);setProposal(false);setMessage(null);if(commit)void save(next);}
  async function read(){const p=propsRef.current;const reply=parseProgramplanUnitPackages(await api.post('/api/programplaner/paketval/lasa',{planId:p.planId}));
    if(reply.planId!==p.planId||reply.units.length!==p.units.length||reply.units.some(u=>!p.units.some(x=>x.id===u.unitId)))throw Error('Fel plan eller skola i svaret.');return reply;}
  function accepts(reply:ProgramplanUnitPackages,revision:number,submitted:ProgramplanPackageEntry[]){const u=reply.units.find(u=>u.unitId===unitId);return reply.planId===props.planId&&reply.units.length===props.units.length&&reply.units.every(u=>props.units.some(x=>x.id===u.unitId))&&u?.revision===revision+1&&equal(u.selections.find(s=>s.blockId===block.id)?.entries??[],submitted);}
  async function save(submitted=valuesRef.current){
    if(busy.current){queued.current=true;return;}if(!writable||!saved||['conflict','unknown','mfa'].includes(stateRef.current)||equal(submitted,baseRef.current))return;
    if(submitted.some(e=>e.distribution.some(d=>d.points.some(p=>!Number.isSafeInteger(p)||p<0)||d.points.reduce((n,p)=>n+p,0)>(levelsOf(e.ref).find(l=>programplanPackageLevelKey(l)===d.levelKey)?.points??0)))){transition('error');setMessage('En nivå har för många eller ogiltiga poäng. Rätta raden först.');return;}
    const revision=propsRef.current.packages?.units.find(u=>u.unitId===unitId)?.revision;if(revision===undefined)return;
    busy.current=true;queued.current=false;transition('saving');setMessage(null);
    const accepted=(reply:ProgramplanUnitPackages)=>{if(!mounted.current)return;propsRef.current={...propsRef.current,packages:reply};propsRef.current.onPackages(reply);baseRef.current=submitted;transition('idle');setMessage('Sparat');};
    try{const reply=parseProgramplanUnitPackages(await api.post('/api/programplaner/paketval',{planId:props.planId,unitId,expectedRevision:revision,blockId:block.id,entries:submitted}));if(!accepts(reply,revision,submitted))throw Error('Obekräftat svar.');accepted(reply);}
    catch(e){if(!mounted.current)return;if(propsRef.current.onSecurityFailure(e)){queued.current=false;transition('error');return;}
      if(e instanceof ApiError&&e.hasExplicitCode){transition(e.code==='mfa_required'?'mfa':e.status===409?'conflict':'error');setMessage(e.status===409?'Skolans paket har ändrats. Dina värden finns kvar. Läs om innan du sparar igen.':e.message);queued.current=false;}
      else{try{const back=await read();if(accepts(back,revision,submitted))accepted(back);else{transition('unknown');setMessage('Sparandet kunde inte bekräftas. Dina värden finns kvar. Läs om skolans paket.');queued.current=false;}}catch(inner){if(propsRef.current.onSecurityFailure(inner)){queued.current=false;transition('error');}else{transition('unknown');setMessage('Sparstatus kunde inte läsas. Läs om skolans paket innan du försöker igen.');queued.current=false;}}}
    }finally{busy.current=false;if(queued.current&&mounted.current){queued.current=false;void save(valuesRef.current);}}
  }
  async function reload(){if(reloading||busy.current||dirty&&!confirmDiscard())return;setReloading(true);try{const back=await read();if(!mounted.current)return;props.onPackages(back);const values=back.units.find(u=>u.unitId===unitId)?.selections.find(s=>s.blockId===block.id)?.entries??EMPTY;baseRef.current=values;valuesRef.current=values;setEntries(values);setProposal(false);transition('idle');setMessage(null);}catch(e){if(!props.onSecurityFailure(e))setMessage('Paketen kunde inte läsas. Försök igen.');}finally{if(mounted.current)setReloading(false);}}
  useEffect(()=>{const t=focusIssue?.target;if(handledFocus.current===focusIssue||t?.kind!=='package'||t.blockId!==block.id||!props.units.some(u=>u.id===t.unitId))return;
    if(unitId!==t.unitId){if(dirty||busy.current)return;setUnitId(t.unitId);const es=props.packages?.units.find(u=>u.unitId===t.unitId)?.selections.find(s=>s.blockId===block.id)?.entries??EMPTY;baseRef.current=es;valuesRef.current=es;setEntries(es);setProposal(false);}
    const handle=requestAnimationFrame(()=>{const section=document.getElementById(`packages-${block.id}`);const entry=t.entryKey?section?.querySelector<HTMLElement>(`[data-package-entry="${CSS.escape(t.entryKey)}"]`):section;const row=t.levelKey?entry?.querySelector<HTMLElement>(`[data-package-level="${CSS.escape(t.levelKey)}"]`):null;const focusedEntry=props.packages?.units.find(u=>u.unitId===t.unitId)?.selections.find(s=>s.blockId===block.id)?.entries.find(e=>!t.entryKey||programplanPackageKey(e.ref)===t.entryKey);const term=focusedEntry?.distribution.find(d=>!t.levelKey||d.levelKey===t.levelKey)?.points.findIndex(p=>p>0)??-1;const control=row?.querySelector<HTMLInputElement>(`input[data-package-term="${term<0?0:term}"]`)??section?.querySelector<HTMLElement>('select');if(control?.getBoundingClientRect().width){(row??section)?.scrollIntoView({block:'center'});control.focus({preventScroll:true});if(document.activeElement===control)handledFocus.current=focusIssue??null;}});return()=>cancelAnimationFrame(handle);
  },[focusIssue,selectedYear,block.id,unitId,dirty,props.packages,props.units]);
  const display=proposal?proposeLanguagePackages(block):entries;
  function propose(){if(dirty&&!confirmDiscard())return;setProposal(true);setMessage('Förslaget är inte sparat. Välj Använd förslaget eller ändra paketen.');}
  function materialized(){return display.map(e=>({...e,distribution:e.distribution.length?e.distribution:suggestPackageDistribution(frame,levelsOf(e.ref))}));}
  function add(){if(!selectedStart)return;try{const ladder=PROGRAMPLAN_LANGUAGE_LADDERS.find(l=>l.id===selectedStart.ladderId)!;const ref=createLanguagePackage(ladder.languageRequired?(ladder.languageCode??language):null,ladder.id,selectedStart.startIndex,block.points);const next=proposal?materialized():entries;if(next.some(e=>programplanPackageKey(e.ref)===programplanPackageKey(ref))){setMessage('Paketet finns redan.');return;}update([...next,{ref,distribution:suggestPackageDistribution(frame,ref.levels)}],true);}catch{setMessage('Det valet kan inte användas i blocket.');}}
  return <section id={`packages-${block.id}`} className="ppk" aria-label={`Paket i ${block.name}`}>
    <div className="ppk-toolbar"><label>Skola <select aria-label={`Skola för ${block.name}`} value={unitId} disabled={state==='saving'||reloading||!!dialog} onChange={e=>{if(dirty&&!confirmDiscard())return;setUnitId(e.target.value);const es=props.packages?.units.find(u=>u.unitId===e.target.value)?.selections.find(s=>s.blockId===block.id)?.entries??EMPTY;baseRef.current=es;valuesRef.current=es;setEntries(es);setProposal(false);transition('idle');setMessage(null);}}>{props.units.map(u=><option key={u.id} value={u.id}>{u.name}{u.inMandate?'':' · läsbehörighet'}</option>)}</select></label>
      <span>{display.length} paket · {block.points} poäng per paket</span>{!writable&&<span>{props.archived?'Arkiverad utbildning':!unit?.inMandate?'Skolan ingår inte i ditt mandat':'Ändring pågår'}</span>}
      {writable&&block.kind==='modernLanguage'&&<button type="button" disabled={locked||state==='saving'} onClick={propose}>Föreslå språkpaket</button>}
      {proposal&&writable&&<button type="button" disabled={locked} onClick={()=>update(materialized(),true)}>Använd förslaget</button>}
    </div>
    {props.packageError?<p role="alert">{props.packageError} <button type="button" onClick={()=>void props.onReadPackages()}>Läs om paket</button></p>:!props.packages?<output>Hämtar skolornas paket…</output>:<>
      {display.map((entry,index)=>{const key=programplanPackageKey(entry.ref),levels=levelsOf(entry.ref),pack=packageOf(entry.ref),label=entry.ref.type==='language'?programplanLanguageName(entry.ref.languageCode):pack?.name??'Paketversion kunde inte läsas',totals=zero();entry.distribution.forEach(d=>d.points.forEach((n,i)=>totals[i]+=n));const mismatch=totals.map((n,i)=>n!==frame[i]);return <section className="ppk-entry" data-package-entry={key} key={key} aria-label={entry.ref.type==='language'?`Språkpaket ${label} ${levels[0]?.itemCode}`:`Valpaket ${label} version ${entry.ref.version}`}><div className="ppk-toolbar"><strong>{label}</strong><span>{entry.ref.type==='package'?`Version ${entry.ref.version} · `:''}{levels.map(l=>programplanPackageLevelName(l)).join(' → ')}</span>{writable&&pack&&canVersion(pack)&&<button type="button" disabled={locked} onClick={()=>setDialog({source:latest(pack)})}>Ny version</button>}{writable&&<><button type="button" disabled={locked} onClick={()=>{const next=proposal?materialized():entries;update(next.map((e,i)=>i===index?{...e,distribution:suggestPackageDistribution(frame,levelsOf(e.ref))}:e),true);}}>Föreslå fördelning</button><button type="button" disabled={locked} aria-label={`Ta bort paket ${label} ${entry.ref.type==='language'?levels[0]?.itemCode:`version ${entry.ref.version}`}`} onClick={()=>update((proposal?materialized():entries).filter((_,i)=>i!==index),true)}>Ta bort</button></>}</div>
        {mismatch.some(Boolean)&&<p className="ppk-hint">Avviker från blockets ram</p>}<table className="ppk-table"><caption className="pp-sr">Paketets nivåer och terminer</caption><thead><tr><th>Nivå</th><th>Poäng</th>{PROGRAMPLAN_TERMS.map((t,i)=><th key={t} className={`ppb-y${Math.floor(i/2)}`}>{t}</th>)}</tr></thead><tbody>{levels.map(level=>{const lk=programplanPackageLevelKey(level),points=entry.distribution.find(d=>d.levelKey===lk)?.points??zero(),over=points.reduce((n,p)=>n+p,0)>level.points;return <tr key={lk} data-package-level={lk} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null)&&!proposal)void save();}}><th scope="row">{programplanPackageLevelName(level)}<small>{level.itemCode}</small></th><td>{level.points}</td>{points.map((n,i)=><td key={i} className={`ppb-y${Math.floor(i/2)}${mismatch[i]||over?' ppk-mismatch':''}`}>{writable?<input data-package-term={i} aria-invalid={mismatch[i]||over} aria-label={`${label} ${level.itemCode}, ${PROGRAMPLAN_TERMS[i]}`} inputMode="numeric" value={n||''} placeholder="·" disabled={locked} onChange={e=>{const next=proposal?materialized():entries;update(next.map((en,ix)=>{if(ix!==index)return en;const p=[...(en.distribution.find(d=>d.levelKey===lk)?.points??zero())] as ProgramplanTermPoints;p[i]=Number(e.target.value.replace(/[^0-9]/gu,''));return{...en,distribution:[...en.distribution.filter(d=>d.levelKey!==lk),{levelKey:lk,points:p}]};}));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>:n||'·'}</td>)}</tr>;})}</tbody></table></section>;})}
      {!display.length&&<p>Inga paket valda för skolan.</p>}
      {writable&&block.kind!=='modernLanguage'&&<fieldset className="ppk-add"><legend>Lägg till valpaket</legend><label>Skolans utbud<select aria-label="Skolans valpaket" value={chosen?`${chosen.packageId}@${chosen.version}`:''} disabled={locked||!props.valpaket} onChange={e=>setSelectedPackage(e.target.value)}>{!offered.length&&<option value="">Inga passande valpaket</option>}{offered.map(p=><option key={`${p.packageId}@${p.version}`} value={`${p.packageId}@${p.version}`}>{p.name} · version {p.version} · {p.points} poäng</option>)}</select></label><button type="button" disabled={locked||!chosen} onClick={addGeneric}>Lägg till valpaket</button>{chosen&&canVersion(chosen)&&<button type="button" disabled={locked} onClick={()=>setDialog({source:latest(chosen)})}>Ny version av valt paket</button>}<button type="button" disabled={locked||!props.valpaket} onClick={()=>setDialog({source:null})}>Nytt valpaket</button></fieldset>}
      {dialog&&block.kind!=='modernLanguage'&&<ProgramplanPackageDialog key={`${unitId}-${dialog.source?.packageId??'new'}-${dialog.source?.version??0}`} scope={`${props.scope}-${props.planId}-${unitId}-${block.id}`} unitId={unitId} units={props.units} role={props.role} kind={block.kind} points={block.points} startedOn={props.startedOn} fixedLevelKeys={fixedLevelKeys} options={options} source={dialog.source} available={props.valpaket?.find(l=>l.unitId===(dialog.source?.unitId??unitId))?.packages??library} onClose={()=>setDialog(null)} onSaved={(list,value)=>{props.onValpaket(list);setSelectedPackage(`${value.packageId}@${value.version}`);setDialog(null);setMessage(`Valpaketet ${value.name}, version ${value.version}, är sparat.`);}} onSecurityFailure={props.onSecurityFailure}/>}

      {writable&&starts.length>0&&<fieldset className="ppk-add"><legend>Lägg till språkpaket</legend>{selectedStart?.ladderId!=='sign'&&<label>Språk<select aria-label="Språk" value={PROGRAMPLAN_LANGUAGE_LADDERS.find(l=>l.id===selectedStart?.ladderId)?.languageCode??language} disabled={locked||!!PROGRAMPLAN_LANGUAGE_LADDERS.find(l=>l.id===selectedStart?.ladderId)?.languageCode||selectedStart?.ladderId==='sign'} onChange={e=>setLanguage(e.target.value)}>{PROGRAMPLAN_LANGUAGES.map(l=><option key={l.code} value={l.code}>{l.name}</option>)}</select></label>}<label>Första nivå<select aria-label="Paketets första nivå" value={selectedStart?`${selectedStart.ladderId}:${selectedStart.startIndex}`:''} disabled={locked} onChange={e=>setStart(e.target.value)}>{starts.map(s=><option key={`${s.ladderId}:${s.startIndex}`} value={`${s.ladderId}:${s.startIndex}`}>{s.name}</option>)}</select></label><button type="button" disabled={locked} onClick={add}>Lägg till paket</button></fieldset>}
    </>}
    {state==='mfa'?<MfaStepUpNotice message={message??'Verifiering med engångskod krävs.'}/>:<output role={state==='idle'?'status':'alert'}>{state==='saving'?'Sparar…':message??(dirty?'Osparade paketändringar':'')}{['conflict','unknown','error'].includes(state)&&<button type="button" onClick={()=>void reload()}>Läs om skolans paket</button>}</output>}
  </section>;
}
